export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
<div className="min-h-screen flex flex-col align-middle justify-center  app-route bg-gradient-to-r from-zinc-500 to-zinc-200 bg-opacity-50 backdrop-blur-lg text-white rounded-lg shadow-lg">

{children}
  
      </div>
  
       
    )
  }
  